In [4]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 3.1 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Using cached tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sulabhyadav/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /Users/sulabhyadav/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Collecting pytz>=2020.1
  Using cached pytz-2026.5-py2.py3-none-any.whl (506 kB)
Requirement already satisfied: six>=1.5 in /Users/sulabhyadav/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, pytz, pandas
Successfully installed pandas-2.3.3 pytz-2026.5 tzdata-2026.5
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np

In [21]:
obj = pd.Series([1,2,3,4,5,6])       #Series - It's a one dimensional array containing a sequence of values, and an associated array of data labels called index 
obj

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [22]:
obj2 = pd.Series([3,5,7,3], index = ["a", "b", "c","d"])
obj2

a    3
b    5
c    7
d    3
dtype: int64

In [23]:
obj2["a"]

np.int64(3)

In [24]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
obj2[obj2 > 0]

a    3
b    5
c    7
d    3
dtype: int64

In [26]:
np.exp(obj2)

a      20.085537
b     148.413159
c    1096.633158
d      20.085537
dtype: float64

In [29]:
sdata = {"Ohio" : 35000, "Texas" : 50000, "Vegas" : 40000, "California": 10000}

states = ["california", "Ohio", "Vegas", "NYC"]

obj3 = pd.Series(sdata, index = states)
obj3

california        NaN
Ohio          35000.0
Vegas         40000.0
NYC               NaN
dtype: float64

In [32]:
 pd.isna(obj3)

california     True
Ohio          False
Vegas         False
NYC            True
dtype: bool

In [33]:
pd.notna(obj3)

california    False
Ohio           True
Vegas          True
NYC           False
dtype: bool

In [38]:
obj4 = pd.Series([4,5,7,89])

In [ ]:
obj4.name = "population"    #assigning name to the obj data

In [42]:
obj4.index = ["Bob", " Steve", "Jeff", "Ryan"]
obj4

Bob        4
 Steve     5
Jeff       7
Ryan      89
Name: population, dtype: int64

In [49]:
#DataFrame
#Rectangular table of data containing an ordered and named collection of data 

data = {"state": ["ohio","ohio", "Ohio", "Nevada", "Nevada","Nevada"],
        "year" : [2000,2001, 2002,2003,2004,2005],
         "pop" : [1.5,6.7,8.9,6.7,6.4,6.0]}


data

{'state': ['ohio', 'ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2003, 2004, 2005],
 'pop': [1.5, 6.7, 8.9, 6.7, 6.4, 6.0]}

In [51]:
frame = pd.DataFrame(data)
frame

    state  year  pop
0    ohio  2000  1.5
1    ohio  2001  6.7
2    Ohio  2002  8.9
3  Nevada  2003  6.7
4  Nevada  2004  6.4
5  Nevada  2005  6.0

In [52]:
frame.head()

    state  year  pop
0    ohio  2000  1.5
1    ohio  2001  6.7
2    Ohio  2002  8.9
3  Nevada  2003  6.7
4  Nevada  2004  6.4

In [53]:
frame.tail()

    state  year  pop
1    ohio  2001  6.7
2    Ohio  2002  8.9
3  Nevada  2003  6.7
4  Nevada  2004  6.4
5  Nevada  2005  6.0